"""Файл - для общей замены текста кнопок клавиатур"""


OPEN_PRE_ORDER = 'Открыть предзаказ'
CLOSE_PRE_ORDER = 'Закрыть предзаказ'
EXCHANGE_RATE = 'Сменить курс'
MARGIN = 'Сменить маржу'
STATUS_PRE_ORDER = 'Просмотреть статусы'
SEND_MESSAGE = 'Отправить сообщение'
ACTIVE_PRE_ORDER = 'Активный предзаказ'
GROUP = 'Сгруппировать'
PROVIDER_HANDLER = 'Отправить поставщику'
PRODUCT = 'Товары'
MY_PRE_ORDER = 'Мои заявки'
PLACE_A_PRE_ORDER = 'Оформить заявку'
MY_SHOPPING_CART = 'Моя корзина'
YES = 'Да'
NO = 'Нет'
IN_SHOPPING_CART = 'В корзину'
HALF = 'Половина бобины'
WHOLE = 'Целая бобина'
DELETE = 'Удалить'
CONFIRM = 'Подтвердить'
DO_NOT_CONFIRM = 'Не подтверждать'
FIRST_STATUS = 'Новый'
SECOND_STATUS = 'Подтвержден'
THIRD_STATUS = 'Не подтвержден'
YES2 = '2Да'
NO2 = '2Нет'
